---
address: 0.0.0.0
pid: tmp/pids/thin.pid
timeout: 120
port: 7002
log: log/thin.log
max_conns: 20480
require: []

max_persistent_conns: 4048
environment: production
servers: 1
daemonize: true
chdir: /home/ilstar/www/colourful_code/current
